name: keylol_flutter
description: keylol.com mobile client by flutter

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0-alpha+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  dio_cookie_manager: ^2.0.0
  path_provider: ^2.0.2
  cookie_jar: ^3.0.1
  html: ^0.15.0
  carousel_slider: ^4.0.0
  cached_network_image: ^3.1.0
  dio_http_cache: ^0.3.0
  flutter_html: ^2.2.1
  webview_flutter: ^2.0.10
  polls: ^1.0.1
  percent_indicator: ^3.0.1
  webview_cookie_manager: ^2.0.1
  video_player: ^2.1.12
  dotted_border: ^2.0.0+1
  badges: ^2.0.2
  url_launcher: ^6.0.17
  html_unescape: ^2.0.0
  flutter_inappwebview: ^5.3.2
  scroll_to_index: ^2.1.1
  chewie: ^1.1.0
  shared_preferences: ^2.0.12
  logger: ^1.1.0
  pretty_json: ^2.0.0
  image_picker: ^0.8.4+4
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  stream_transform: ^2.0.0
  bloc_concurrency: ^0.2.0
  pull_to_refresh: ^2.0.0
  flutter_markdown: ^0.6.9
  html2md: ^1.2.5
  sqflite: ^2.0.2
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - images/unknown_avatar.jpg
    - images/slide_view_placeholder.jpg
    - images/forum.gif
    - images/quote_proper_left.png
    - images/quote_proper_right.png
    - images/splash.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
