# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup java environment
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      # Setup flutter environment
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      # Build
      - name: Build 
        run: |
          flutter pub get
          flutter build apk
          
      # Nightly Release
      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: "KeylolF Nightly Release"
          prerelease: true
          file: |
            ./build/app/outputs/flutter-apk/app-release.apk
